### ISSUE TITLE
Breaks History Controller

### ISSUE THREAD

**Issue by LABCAT** [Quinn-Interactive/silverstripe-seo#46]
When this module is installed it is not possible to view the individual history of a page as the following JS error occurs:
"bundle.js?m=1569294451:1 Uncaught (in promise) Error: Injector.get(): Component GoogleSearchPreview does not exist"

I resolved this in my project by adding the following to the getCMSFields in Page.php:
`if(Controller::curr() instanceof HistoryViewerController){
            $fields->removeByName('SEOHealthAnalysis');
 }`

There may be a better way as this removes the SEOHealthAnalysis from history completely.

**Comment by oddnoc** [comment]
We noticed this issue as well and have a fix on the bugfix/history-fix branch. Our current approach is the same as yours: removing the fields from history.

**Comment by oddnoc** [comment]
This is fixed in 1.0.7
