### ISSUE TITLE
A problem with this module is causing CSS styling issues in the CMS Pages interface

### ISSUE THREAD

**Issue by mooror** [Quinn-Interactive/silverstripe-seo#47]
## The Problem
A problem with this module is causing the `debug.css` file to used on the CMS Pages (edit) interface which in turn causes styling issues

## Steps to reproduce
1. Login to the CMS (admin/)
2. Travel to the Pages section using the left hand navigation (admin/pages/)
3. Click on one of your pages in the Sitetree to edit it (admin/pages/edit/show/1)
4. Look closely at the styles of the CMS interface

### Before Installation
Here is how the CMS Pages edit interface should look (in SS4)
![firefox-cms-pages-edit-styles-normal](https://user-images.githubusercontent.com/6110819/71692982-90f44e00-2d68-11ea-9a05-c27da2250782.png)

### After Installation
And here is what it currently looks like (some styling issues are highlighted in yellow).
The most noticeable difference is the **font size** and the **left hand menu** (which has items jutting out)
![firefox-cms-pages-edit-styles-bug](https://user-images.githubusercontent.com/6110819/71692974-8cc83080-2d68-11ea-8a70-d21c49561cda.png)

### The Stylesheet causing the issue
You can see that the `debug.css` file is being included. If you disable its styles using the developer tools the styling issues will be fixed. 
![firefox-console-debug-css](https://user-images.githubusercontent.com/6110819/71693168-006a3d80-2d69-11ea-9395-0b456ff94a15.png)

## Possible Explanation
I originally brought this problem up over in the Silverstripe Slack channel ([see this conversation](https://silverstripe-users.slack.com/archives/C36U3BDHN/p1577996018142100)) because I thought that it may be a framework bug (because `debug.css` is from the silverstripe framework). However when I discussed this issue with Andy he explained to me that this stylesheet is only included when the debug class (`SilverStripe\Dev\Debug`) is included or when an error has occurred.

**Comment by oddnoc** [comment]
This is fixed in version 1.0.7
