### ISSUE TITLE
template path is wrong (SS4.5.2)

### ISSUE THREAD

**Issue by guyvanbael** [Quinn-Interactive/silverstripe-seo#50]
When updating recipe-cms. Internal server error occurs with this message
`2020-04-14 08:22:49] error-log.WARNING: E_USER_WARNING: None of the following templates could be found: QuinnInteractive\Seo\Forms\HealthAnalysisField in themes "Array (     [0] => silverstripe/admin:cms-forms     [1] => $default ) " {"code":512,"message":"None of the following templates could be found: QuinnInteractive\\Seo\\Forms\\HealthAnalysisField in themes \"Array\n(\n    [0] => silverstripe/admin:cms-forms\n    [1] => $default\n)\n\"","file":"/Volumes/guySSD/webroot/carrewiel/vendor/silverstripe/framework/src/View/SSViewer.php","line":215} []`
It seems dat the path to the template still has "Vulcan" in it. This should be changed into "QuinnInteractive" to fix it

**Comment by oddnoc** [comment]
Could you test the bug-fix branch by requiring `dev-bugfix/50-template-path` and letting us know how it goes? Thanks!

**Comment by guyvanbael** [comment]
@oddnoc Just tested on new SS4.5.2 project and it's working
