### ISSUE TITLE
tags not showing

### ISSUE THREAD

**Issue by guyvanbael** [Quinn-Interactive/silverstripe-seo#52]
Installed the module, added some data, but no opengraph tags are in the code. In Page.ss there's $MetaTags(false)
(ss4.5.2)
@oddnoc   SOLUTION: in PageSeoExtension.php (line 75). Rename function getMetaTags to MetaTags
i created a pull request for this :-)

**Comment by oddnoc** [comment]
Pull request merged. New release forthcoming.
